services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules # Prevent host's node_modules from overriding container's
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Improves hot reload reliability in containers

